### ISSUE TITLE
Middle Element of Linked List

### ISSUE THREAD

**Issue by nehalgupta8501** [ahampriyanshu/algo_ds_101#1408]
**Submission Title**
Middle Element of Linked List

**Submission Type**
Data Structure

**Submission Description**
Find the middle element in a singly linked list

**Submission Directory**
Data_Structures=>Linked_List=>Singly_Linked_List

**Contributors**

- [ ]  C++ -
- [ ]  C -
- [ ]  Python -
- [ ] Java - 
- [ ] JavaScript -
- [ ] TypeScript -
- [ ] Golang -
- [ ] Ruby -
- [ ] php -
- [ ] Swift -
- [ ] C# -

**Comment by divyagupta-98** [comment]
I would like to do this in python

**Comment by parjanyaacoder** [comment]
I would like to work on this issue in Java. Pls assign.

**Comment by amal-majunu** [comment]
Can I work on this issue in C++?

**Comment by maityankan10** [comment]
can I work this in c++

**Comment by ahampriyanshu** [comment]
> can I work this in c++

Please opt a different language/issue.

**Comment by rishika-singh49** [comment]
I would like to work  on this in c ?
can i do it ?

**Comment by andre-silva-14** [comment]
Ok, Cloned the repo in a Linux VM and it is not working, this repo is not compatible with Windows. You can assign me JavaScript/Typescript if available.

**Comment by Utkarshn10** [comment]
@nehalgupta8501 I would like to take  it for java

**Comment by ahampriyanshu** [comment]
> Ok, Cloned the repo in a Linux VM and it is now working, this repo is not compatible with Windows. You can assign me JavaScript/Typescript if available.

Hi @andre-silva-14 ,
Can name folder/file creating this issue.

**Comment by andre-silva-14** [comment]
Hi @ahampriyanshu,
Sure, I believe that the file creating this issue is:

- `algo_ds_101/Data_Structures/Linked_List/Singly_Linked_List/Delete_Kth_Node_From_End => Delete_Kth_Node_From_End.cpp` (commited 5 days ago)

The `=>` in the filename breaks the cloning and makes it pretty much impossible to work on a windows machine.
You can find [here](https://stackoverflow.com/questions/1976007/what-characters-are-forbidden-in-windows-and-linux-directory-names#answer-31976060) a reference to which filename chars are forbidden in each OS.

**Comment by ahampriyanshu** [comment]
Thank you very much @andre :smile:

**Comment by ahampriyanshu** [comment]
thanks everyone :v:
