### ISSUE TITLE
Josephus problem

### ISSUE THREAD

**Issue by vikashpatel07** [ahampriyanshu/algo_ds_101#1764]
### Type

Algorithm

### Directory

Algorithm => Recursion

### Description

There are n people standing in a circle waiting to be executed. The counting out begins at some point in the circle and proceeds around the circle in a fixed direction. In each step, a certain number of people are skipped and the next person is executed. The elimination proceeds around the circle (which is becoming smaller and smaller as the executed people are removed), until only the last person remains, who is given freedom. Given the total number of persons n and a number k which indicates that k-1 persons are skipped and kth person is killed in circle. The task is to choose the place in the initial circle so that you are the last one remaining and so survive.

### Programming Language

- [X] c++
- [ ] c
- [ ] python
- [ ] java
- [ ] kotlin
- [ ] javascript
- [ ] typescript
- [ ] c#
- [ ] swift
- [ ] ruby
- [ ] scala
- [ ] go
- [ ] php
- [ ] haskell
- [ ] bash

**Comment by shubhamhere** [comment]
Assign me for solution in C++ . Happy to contribute : )

**Comment by dittapandey** [comment]
Assign me for solution in c++

**Comment by DarkRaiCodes** [comment]
please assign me this :)

**Comment by the-kaushal-agrawal** [comment]
pls assign me this

**Comment by Siddhantmehta2003** [comment]
I have the solution in java please feel free to assign it to me...

**Comment by vaishnavyogesh** [comment]
# Type
Algorithm

# Directory
Algorithm => Recursion

# Description
There are n people standing in a circle waiting to be executed. The counting out begins at some point in the circle and proceeds around the circle in a fixed direction. In each step, a certain number of people are skipped and the next person is executed. The elimination proceeds around the circle (which is becoming smaller and smaller as the executed people are removed), until only the last person remains, who is given freedom. Given the total number of persons n and a number k which indicates that k-1 persons are skipped and kth person is killed in circle. The task is to choose the place in the initial circle so that you are the last one remaining and so survive.

# Programming Language

- [ ]  c++

 

- [ ] c

 

- [ ] python

- [ ]  java

 

- [x] kotlin

 

- [ ] javascript

 

- [ ] typescript

- [ ] c#

 

- [ ] swift

 

- [ ] ruby

 

- [ ] scala

 

- [ ] go

 

- [ ] php

- [ ] haskell

 

- [ ] bash

**Comment by vaishnavyogesh** [comment]
Kotlin => 1 Day

**Comment by Heisenberg-Vardan** [comment]
I can solve this in python please assign

**Comment by ritesh-karankal** [comment]
Hey! Can I add the javascript solution for the problem?

**Comment by Karssido** [comment]
Hey, Please assign me this issue. I will add a Python3 solution for the same.

**Comment by esheetaparulekar** [comment]
Hello, can I work on this issue in Java?

**Comment by vaishnavyogesh** [comment]
**Added => josephus.kt**  #1778

**Comment by himanshukaushal123** [comment]
Please assign this issue to me...

**Comment by PrakashAditya17** [comment]
I can do this in java

**Comment by Tanushreesuthar** [comment]
assign me in go

**Comment by Tanushreesuthar** [comment]
please assign me in c#

**Comment by chehak123** [comment]
can i work on this issue in c++?
